title: Woo Min Kim
logo: ego.png
show_downloads: false
google_analytics: G-3E25WR3VM2
theme: jekyll-theme-minimal
kramdown:
  math_engine: mathjax
sass:
  sass_dir: assets/css
  style: expanded # compressed  # Or 'expanded' for readable output